import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./data/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2a2c",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-low": "#1c1b1d",
        surface: "#131315",
        "inverse-primary": "#494bd6",
        "on-tertiary-fixed": "#191c1d",
        "surface-container-highest": "#353437",
        "tertiary-fixed-dim": "#c5c7c8",
        primary: "#c0c1ff",
        "inverse-surface": "#e5e1e4",
        background: "#131315",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary-container": "#272a2b",
        "on-background": "#e5e1e4",
        "on-primary-fixed": "#07006c",
        "inverse-on-surface": "#313032",
        "surface-dim": "#131315",
        "on-secondary-fixed": "#002113",
        "secondary-fixed-dim": "#4edea3",
        "on-surface-variant": "#c7c4d7",
        "surface-container-lowest": "#0e0e10",
        "outline-variant": "#464554",
        "tertiary-container": "#8f9192",
        outline: "#908fa0",
        "on-surface": "#e5e1e4",
        error: "#ffb4ab",
        "surface-container": "#201f22",
        "surface-tint": "#c0c1ff",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353437",
        "primary-container": "#8083ff",
        "on-tertiary-fixed-variant": "#454748",
        "secondary-container": "#00a572",
        "on-primary": "#1000a9",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-container": "#0d0096",
        "primary-fixed": "#e1e0ff",
        tertiary: "#c5c7c8",
        "surface-bright": "#39393b",
        "error-container": "#93000a",
        "on-secondary": "#003824",
        "on-secondary-container": "#00311f",
        secondary: "#4edea3",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary": "#2e3132",
        "on-error": "#690005",
        "tertiary-fixed": "#e1e3e4"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1200px",
        "margin-mobile": "20px",
        base: "8px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "section-gap": "120px",
        "stack-sm": "12px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        body: ["Inter", "system-ui", "sans-serif"],
        display: ["Geist", "Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
